"""Stable serialized enum values."""
from enum import StrEnum

class UAVRole(StrEnum):
    SCOUT = "SCOUT"
    RELAY = "RELAY"
    BACKUP_RELAY = "BACKUP_RELAY"
    EMERGENCY_SCOUT = "EMERGENCY_SCOUT"
    RETURN_TO_HOME = "RETURN_TO_HOME"
    IDLE = "IDLE"

class FailureStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    LOST = "LOST"

class RecoveryState(StrEnum):
    NORMAL = "NORMAL"
    DEGRADED = "DEGRADED"
    FAILURE_DETECTED = "FAILURE_DETECTED"
    RECONFIGURING = "RECONFIGURING"
    RECOVERED = "RECOVERED"

class TaskStatus(StrEnum):
    PENDING = "PENDING"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class TaskType(StrEnum):
    SURVEY = "SURVEY"
    EMERGENCY_SURVEY = "EMERGENCY_SURVEY"

class HandoverState(StrEnum):
    NONE = "NONE"
    PENDING = "PENDING"
    PREPARING = "PREPARING"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"

class RTHState(StrEnum):
    NONE = "NONE"
    REQUESTED = "REQUESTED"
    RETURNING = "RETURNING"
    ARRIVED = "ARRIVED"

class EventType(StrEnum):
    UAV_FAILURE = "UAV_FAILURE"
    LINK_FAILURE = "LINK_FAILURE"
    LINK_DEGRADATION = "LINK_DEGRADATION"
    PACKET_LOSS_BURST = "PACKET_LOSS_BURST"
    EMERGENCY_POI = "EMERGENCY_POI"
    BATTERY_WARNING = "BATTERY_WARNING"
    MISSION_START = "MISSION_START"
    MISSION_END = "MISSION_END"
