"""Authoritative string-backed enums for AetherSwarm."""
from enum import Enum


class Role(str, Enum):
    IDLE = "IDLE"
    SCOUT = "SCOUT"
    SURVEYOR = "SURVEYOR"
    RELAY = "RELAY"
    EMERGENCY_SCOUT = "EMERGENCY_SCOUT"


class TaskStatus(str, Enum):
    PENDING = "PENDING"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETE = "COMPLETE"
    DEFERRED = "DEFERRED"
    UNREACHABLE = "UNREACHABLE"


class FailureState(str, Enum):
    NORMAL = "NORMAL"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    RECOVERING = "RECOVERING"


class RTHState(str, Enum):
    NONE = "NONE"
    REQUIRED = "REQUIRED"
    ACTIVE = "ACTIVE"
    COMPLETE = "COMPLETE"


class HandoverState(str, Enum):
    NONE = "NONE"
    HANDOVER_PENDING = "HANDOVER_PENDING"
    PREPARING = "PREPARING"
    VERIFYING = "VERIFYING"
    COMPLETE = "COMPLETE"


class RejectionCode(str, Enum):
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    ILLEGAL_LIFECYCLE_TRANSITION = "ILLEGAL_LIFECYCLE_TRANSITION"
    GEOFENCE_VIOLATION = "GEOFENCE_VIOLATION"
    COLLISION_RISK = "COLLISION_RISK"
    INSUFFICIENT_ENERGY = "INSUFFICIENT_ENERGY"
    LOCKED_ROLE = "LOCKED_ROLE"
    LOCKED_ASSIGNMENT = "LOCKED_ASSIGNMENT"
    STALE_TICK_PROPOSAL = "STALE_TICK_PROPOSAL"
    CONFLICTING_COMMAND = "CONFLICTING_COMMAND"
    CONNECTIVITY_INFEASIBLE = "CONNECTIVITY_INFEASIBLE"


class SortieState(str, Enum):
    READY = "READY"
    ACTIVE = "ACTIVE"
    RTH = "RTH"
    LANDING = "LANDING"
    LANDED = "LANDED"
    RECHARGING = "RECHARGING"


class EventType(str, Enum):
    SIMULATION_STEP = "SIMULATION_STEP"
    UAV_ACTIVATED = "UAV_ACTIVATED"
    UAV_FAILED = "UAV_FAILED"
    UAV_LANDED = "UAV_LANDED"
    UAV_RECHARGING = "UAV_RECHARGING"
    UAV_RECHARGED = "UAV_RECHARGED"
    SORTIE_STARTED = "SORTIE_STARTED"
    SORTIE_COMPLETED = "SORTIE_COMPLETED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STARTED = "TASK_STARTED"
    TASK_PROGRESS = "TASK_PROGRESS"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_DEFERRED = "TASK_DEFERRED"
    TASK_HANDOFF = "TASK_HANDOFF"
    TASK_REASSIGNED = "TASK_REASSIGNED"
    RTH_TRIGGERED = "RTH_TRIGGERED"
    COMMAND_REJECTED = "COMMAND_REJECTED"
    POI_DETECTED = "POI_DETECTED"
    TELEMETRY_DELIVERED = "TELEMETRY_DELIVERED"
    TELEMETRY_DEADLINE_EXCEEDED = "TELEMETRY_DEADLINE_EXCEEDED"
    SEPARATION_INTERVENTION = "SEPARATION_INTERVENTION"
    GEOFENCE_INTERVENTION = "GEOFENCE_INTERVENTION"
    RELAY_ASSIGNED = "RELAY_ASSIGNED"
    RELAY_RELEASED = "RELAY_RELEASED"
    RELAY_HANDOFF = "RELAY_HANDOFF"
    RELAY_LOST = "RELAY_LOST"
    RELAY_RECOVERY = "RELAY_RECOVERY"
    COMMUNICATION_REPLAN = "COMMUNICATION_REPLAN"
    TASK_CONNECTIVITY_DEFERRED = "TASK_CONNECTIVITY_DEFERRED"
    DEPARTURE_QUEUED = "DEPARTURE_QUEUED"
    DEPARTURE_STARTED = "DEPARTURE_STARTED"
    DEPARTURE_CLEARED = "DEPARTURE_CLEARED"


class TelemetryStatus(str, Enum):
    PENDING = "PENDING"
    DELIVERED = "DELIVERED"
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
